### ISSUE TITLE
REST statt JSON-RPC

### ISSUE THREAD

**Issue by truh** [truh/BigPicture#2]
Könnte geeigneter sein.
- Evaluieren
- Falls geeignet -> redesign

**Comment by mhaidn-tgm** [comment]
---

## REST

_Representational State Transfer_, konzentriert sich im Gegensatz zu _SOAP_, das auch gerne für HTTP-Requests verwendet wird auf die URL am Server.
Die folgenden HTTP-Üblichen Methoden stehen zur Verfügung:
- GET
- POST
- ADD
- PUT
- DELETE 

Aufruf-Möglichkeit via Javascript:

Datentyp

```
function Contact(fName, lName, eMail, id) {
    this.fName = fName;
    this.lName = lName;
    this.eMail = eMail;
    this.ContactId = id;
    this.toJsonString = function () { return JSON.stringify(this); };
};
```

Hinzufuegen:

```
function addContact (contact) {

     jQuery.ajax({
         type: "ADD",
         url: "http://localhost:49193/Contacts.svc/Add",
         data: contact.toJsonString(),
         contentType: "application/json; charset=utf-8",
         dataType: "json",
         success: function (data, status, jqXHR) {
              // do something
         },

         error: function (jqXHR, status) {           
              // error handler
         }

     });
}
```

Da REST allem Anschein nach rein verzeichnis- und file-basiert ist, stellt sich die Frage ob diese Architektur, zwecks Persistierung der Daaten die Richtige für unser Projekt ist.
Bzw. ob sich das Redesign für den minimal größeren Funktionsumfang auszahlt.

**Comment by truh** [comment]
So wie ich es verstanden hab ist der Unterschied in Wahrheit nur oberflächlich. 
Der Methodenname ist nicht teil der Daten sondern wird halt als Teil der URL angegeben.

**Comment by truh** [comment]
In Planung eingegangen, wird geschlossen.
